### ISSUE TITLE
Fresh Docker install :  We're sorry, but something went wrong.

### ISSUE THREAD

**Issue by gerroon** [chrisvel/wreeto_official#40] opened 2020-08-07 03:06 UTC
Hi

I followed the docker-compose steps to install this. I added admin user with a password. I can login alright. When I try to create a Project I get the line above and the log below. 

I am accessing it over my VPN network so no reverse proxy or serving over web server.

In fact adding a project or deleting categories gives me that errors

```

We're sorry, but something went wrong.

If you are the application owner check the logs for more information.

```

```

eturns_integer =  true. To disable this message and keep the current (boolean) behaviour of 'exists' you can set `Redis.exists_returns_integer = false`, but this option will be removed in 5.0. (/usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/launcher.rb:160:in `block (2 levels) in ❤')
postgres_1  | 2020-08-07 03:03:17.650 UTC [34] ERROR:  duplicate key value violates unique constraint "index_categories_on_slug_and_user_id"
postgres_1  | 2020-08-07 03:03:17.650 UTC [34] DETAIL:  Key (slug, user_id)=(xxx, 1) already exists.
postgres_1  | 2020-08-07 03:03:17.650 UTC [34] STATEMENT:  INSERT INTO "categories" ("title", "description", "user_id", "parent_id", "slug", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"
```

thanks

**Comment by chrisvel** [comment] 2020-08-07 14:27
Hi @gerroon,

thanks for opening this issue. I did a research and found out that the problem occurs because of code cleanup I did some weeks ago, removing unnecessary notification mailers. 

The "We're sorry..." error appears but finally the category gets created or deleted. For the record, the logs you provided has less to do with the root of the problem and more to do with the consequence of not knowing the category has been created after the error was displayed and trying to create it again. 

I patched the issue and created a new docker image (master or v2.3.5). You can just `docker-compose pull` and `docker-compose up -d` again to get the latest changes and restart the docker containers, you'll be able to create/update/delete categories without issues.

Let me know If that works.

**Comment by gerroon** [comment] 2020-08-07 15:59
Hi

Thanks for the fix but that did not solve the issue ti seems , I still get the same error when I try to create a project and no logging is shown in the terminal when that happens.

**Comment by chrisvel** [comment] 2020-08-07 19:27
@gerroon Can you try to pull via docker-compose once more and then `docker-compose down` and `docker-compose up` ?

I created a new clean Ubuntu VM and followed the same steps - I can't reproduce the issue now. I 've also added a validation error when someone tries to create a duplicate category with symbol differences e.g. "my category" and "my category !". 

Can you please try again? I believe the containers must have not be destroyed and created again.

**Comment by gerroon** [comment] 2020-08-07 19:55
I did a pull but I am not seeing any new images? Btw I actually did compose down prior to running the updated images.

**Comment by chrisvel** [comment] 2020-08-10 08:41
Please try to pull again with `docker pull chrisvel/wreeto`, then compose down and up. I guess that you still must be running an old version. I tried again with a new install on a new virtual machine and I am not getting any issues creating or deleting categories. If it still happens, can you please share some more information (logs) ?

**Comment by gerroon** [comment] 2020-08-10 15:12
```
docker pull chrisvel/wreeto:latest
latest: Pulling from chrisvel/wreeto
Digest: sha256:40e07e6e6384d4c31e9f6d8af4999b6cef5e142f72227bf2e3c7c5ac7ce450dd
Status: Image is up to date for chrisvel/wreeto:latest
docker.io/chrisvel/wreeto:latest

```

I really do not see a new version

**Comment by chrisvel** [comment] 2020-08-10 15:24
You must have the latest one then. Can you prune the `chrisvel/wreeto` and `postgres` images and try to pull them again ?

**Comment by chrisvel** [comment] 2020-09-11 10:07
Resolving for now as it's been idle for over 20 days

**Closed as completed** 2020-09-11 10:07 UTC
Labels: bug
